[package]
name = "usync"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["kprotty"]
readme = "README.md"
homepage = "https://github.com/kprotty"
documentation = "https://docs.rs/usync"
description = "(WIP) synchronization library"
categories = ["concurrency", "data-structures"]
keywords = [
    "lock", "mutex", "rwlock", "condvar", "once",
    "parallel", "parallelism", "thread", "concurrent", "performance",
]

[dependencies]
once_cell = "1"