[package]
name = "benchmark"
version = "0.0.0"
edition = "2021"
publish = false
license = "Apache-2.0"
authors = ["kprotty"]

[dependencies]
parking_lot = "0.12.1"
simple-mutex = "1.1"
once_cell = "1"

[[bench]]
name = "mutex"
path = "./mutex/mod.rs"
harness = false
